language: python
python:
  - '2.7'
virtualenv:
  system_site_packages: true

addons:
  chrome: stable

# Stub: do nothing
before_install:
  - ls
install:
  - ls

before_script:
  - cd ..
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.90.zip -nv
  - unzip -q google_appengine_1.9.90.zip
  - export SDK_LOCATION="$(pwd)/google_appengine"
  - wget https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip
  - unzip -q chromedriver_linux64.zip
  - cp chromedriver $HOME/bin/
  - cd $TRAVIS_BUILD_DIR
  - python $SDK_LOCATION/dev_appserver.py --skip_sdk_update_check 1 . &
  - pip install selenium pytest
script:
  - pytest tests -v

before_deploy:
  - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
    -in client-secret.json.enc -out ../client-secret.json -d
  - version=$(if [ ! -z "$TRAVIS_TAG" ]; then echo $(cut -d'-' -f2 <<<"$TRAVIS_TAG");
    else echo "$TRAVIS_BRANCH"; fi)
  - echo "Version = $version"
deploy:
  provider: gae
  keyfile: "../client-secret.json"
  project: sympy-live-hrd
  skip_cleanup: true
  no_promote: true
  version: "$version"
  on:
    all_branches: true
    repo: sympy/sympy-live

after_deploy:
  - pip install requests
  - python bin/update_status_on_pr.py
